version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cloud@123$
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./taskdb.sql:/docker-entrypoint-initdb.d/taskdb.sql

  backend:
    build: ./teamflow-backend/teamflow-backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Cloud@123$
    depends_on:
      - db
    # optional: remove command if using Dockerfile CMD
    # command: >

  frontend:
    build: ./taskmanage/my-app
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: